---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: Ubuntu-20.04
    steps:

      - name: Test
        env:
          DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo ${#DOCKERHUB_USER}
          echo ${#DOCKERHUB_TOKEN}
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
